### ISSUE TITLE
ORDER BY DESC

### ISSUE THREAD

**Issue by zkwbbr** [atlasphp/Atlas.Query#10]
I don't think this is [documented](http://atlasphp.io/cassini/query/select.html) but is sorting done like this?

```
$select
    ->orderBy('foo DESC')
```

It appears to work but just want to make sure if this is the intended way.

**Comment by pmjones** [comment]
It is the intended way; I looked, and it is in fact documented: http://atlasphp.io/cassini/query/select.html#1-4-3-1-7 (but there's a lot that page, so easy to miss). Hope that helps!

**Comment by froschdesign** [comment]
@pmjones 
I think he means that no example shows the use with `DESC`.

**Comment by pmjones** [comment]
@froschdesign Oh, I see! Yes @zkwbbr the example you show is correct; I will add that to the docs (or you can send a PR withe the change, so you get the credit on Github).

**Comment by zkwbbr** [comment]
@pmjones Sent at PR, thanks.
