### ISSUE TITLE
Auto reset query after fetch*() is called?

### ISSUE THREAD

**Issue by kabatak** [atlasphp/Atlas.Query#2]
Is it possible to auto reset() queries when fetch*() is called?
In this use-case I have to use reset(); every time:

```
class Sample
{
    private $select;
	
    public function __construct($pdo)
    {
        $this->select = Select::new($pdo);
    }

    public function foo()
    {
        $this->select->reset();		
		
        return $this->select->columns('*')->from('table')->where('col =', 'foo' )->fetchAll();
    }

    public function bar()
    {
        $this->select->reset();		
		
        return $this->select->columns('*')->from('table')->->where('col =', 'bar' )->fetchAll();
    }
}
```
Thanks :100:

**Comment by froschdesign** [comment]
@kabatak 
> In this use-case…

Right, in _this_ case, but others will fail.

Example:
```php
$select->columns('*')->from('table')->fetchAll();
$select->fetchAffected();

**Comment by kabatak** [comment]
> 
> 
> @kabatak
> 
> > In this use-case…
> 
> Right, in _this_ case, but others will fail.
> 
> Example:
> 
> ```
> $select->columns('*')->from('table')->fetchAll();
> $select->fetchAffected();
> ```

Sorry but I don't understand what you mean.

**Comment by froschdesign** [comment]
@kabatak 
> Is it possible to auto reset() queries when fetch*() is called?

If a reset is called automatically after the fetch method, my example fails.

**Comment by pmjones** [comment]
@kabatak Of curiosity, why do you prefer reset() over creating a new Select object? E.g.:

```php
class Sample
{
    private $pdo;
	
    public function __construct($pdo)
    {
        $this->pdo = $pdo;
    }

    public function foo()
    {
        return Select::new($this->pdo)->columns('*')->from('table')->fetchAll();
    }

    public function bar()
    {
        return Select::new($this->pdo)->columns('*')->from('table')->fetchAll();
    }
}
```

**Comment by kabatak** [comment]
@pmjones 
Well, I just prefer the child class of Sample to not access $pdo. E.g.,

```
class Child extends Sample
{
	public function qux()
	{
		return Select::new($this->pdo)->...
	}
}
```

but I think that might just do it for now.

**Comment by pmjones** [comment]
> I just prefer the child class of Sample to not access $pdo.

Totally understandable. This is where a factory method becomes useful, maybe something like the following:

```php
class Sample
{
    private $pdo;
	
    public function __construct($pdo)
    {
        $this->pdo = $pdo;
    }

    protected function newSelect()
    {
        return Select::new($this->pdo);
    }
}

class Child extends Sample
{
    public function qux()
    {
        return $this->newSelect()->...
    }
}
```

(This is almost identical to what the Atlas Table and Mapper classes do.)

**Comment by kabatak** [comment]
@pmjones Thanks I'll use factory instead :-)
