### ISSUE TITLE
How to do transactions?

### ISSUE THREAD

**Issue by zkwbbr** [atlasphp/Atlas.Query#4]
Is it supposed to be done in the PDO object? E.g.,

```
$pdo = new \PDO('...');
$pdo->beginTransaction();
$insert = Insert::new($pdo);
// do transaction stuff ...
$pdo->commit();
```
Or, is there another recommended way within the Atlas.Query class? Thanks.

**Comment by pmjones** [comment]
I'm so sorry to have left this for so long.

You are correct: the Query system does not provide any transaction management functionality; you have to manage them yourself.

Again, my apologies for the very long delay.
