### ISSUE TITLE
Support CTEs

### ISSUE THREAD

**Issue by Bilge** [atlasphp/Atlas.Query#8]
If we look at the [syntax of a SELECT statement](https://www.postgresql.org/docs/12/sql-select.html), we see an optional *WITH* clause before the SELECT keyword. I've linked to the Postgres docs, but this is actually standard across all implementations I've encountered. This feature is called *common table expressions*. I often use it to inject static data into queries (instead of storing unchanging data in the database). However, it appears the `Select` builder does not support CTEs at all.

**Comment by pmjones** [comment]
>  it appears the Select builder does not support CTEs at all.

If you'd like to send along a pull request to add support, I'll be happy to review it!

**Comment by pmjones** [comment]
This is going into the 2.x branch; see https://github.com/atlasphp/Atlas.Query/blob/2.x/src/Query.php#L124-L140 and https://github.com/atlasphp/Atlas.Query/blob/2.x/src/Clause/Component/With.php
